# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 1) do

  create_table "actors", :force => true do |t|
    t.column "name",  :text
    t.column "phone", :text
  end

  create_table "bookings", :force => true do |t|
    t.column "actor_id",   :integer
    t.column "room_id",    :integer
    t.column "project_id", :integer
    t.column "booked_at",  :datetime
  end

  create_table "projects", :force => true do |t|
    t.column "name", :text
  end

  create_table "rooms", :force => true do |t|
    t.column "name", :text
  end

end
