# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 3) do

  create_table "grades", :force => true do |t|
    t.column "salesperson_id",    :integer
    t.column "training_class_id", :integer
    t.column "percentage_grade",  :integer
    t.column "took_class_at",     :datetime
  end

  create_table "salespeople", :force => true do |t|
    t.column "name",     :string, :limit => 45
    t.column "employer", :string, :limit => 45
  end

  create_table "training_classes", :force => true do |t|
    t.column "name", :string, :limit => 45
  end

end
